monolog:
  handlers:
    app:
      type: stream
      path: "php://stderr"
      level: info

    # ğŸ” Login/auth Ğ´ÑĞ»Ğ³ÑÑ€ÑĞ½Ğ³Ò¯Ğ¹ Ğ»Ğ¾Ğ³
    security_debug:
      type: stream
      path: "php://stderr"
      level: debug
      channels: ["security"]
